In [1]:
import pandas as pd
import numpy as np

In [2]:
# min\\(s1*w1 + s2*w2) - y(truth)\\^2  (s is the submission, w is corresponding weight)
# Want to get W(Matrix of w)
# Since minimize (SW - y)T (SW - y) -> W = (ST * S)^-1 * ST * y
# ST * y = K * [(2*correct_rate ) -1 ]


In [3]:
# First try, ensemble two submissions
sub_1 = pd.read_csv('EE627_final_ver8.csv')
sub_2 = pd.read_csv('EE627_final_ver10.csv') 

In [5]:
# Replace 0 by -1
sub_1.Predictor.replace(0,-1,inplace= True)
sub_2.Predictor.replace(0,-1,inplace= True)

In [6]:
sub_1

TrackID  Predictor
0       199810_208019         -1
1        199810_74139          1
2         199810_9903         -1
3       199810_242681         -1
4        199810_18515          1
5       199810_105760          1
6       199812_276940         -1
7       199812_142408          1
8       199812_130023          1
9        199812_29189         -1
10      199812_223706          1
11      199812_211361         -1
12      199813_188441          1
13       199813_20968         -1
14       199813_21571          1
15       199813_79640          1
16      199813_184173         -1
17      199813_111874         -1
18      199814_122375         -1
19      199814_189043          1
20      199814_122429         -1
21       199814_52519         -1
22      199814_232332          1
23      199814_262193          1
24       199815_64345         -1
25      199815_118841         -1
26      199815_275682          1
27       199815_30062          1
28      199815_258473          1
29      199815_129866         -1
...               ...        ...
119970  248990_255923         -1
119971   248990_61561         -1
119972  248990_133208         -1
119973  248990_285661          1
119974   248990_49802          1
119975   248990_87552          1
119976   248993_87854         -1
119977   248993_65792         -1
119978  248993_192625          1
119979   248993_60331          1
119980   248993_96932         -1
119981  248993_169455          1
119982  248996_125502         -1
119983  248996_130097          1
119984   248996_27528          1
119985   248996_13479         -1
119986   248996_92369         -1
119987  248996_177384          1
119988    249008_4967          1
119989  249008_164591          1
119990  249008_127497         -1
119991  249008_165413          1
119992  249008_197975         -1
119993  249008_239621         -1
119994  249010_110470          1
119995   249010_72192         -1
119996   249010_86104         -1
119997  249010_186634          1
119998  249010_293818         -1
119999  249010_262811          1

[120000 rows x 2 columns]

In [8]:
s_1 = sub_1.Predictor.tolist()
s_2 = sub_2.Predictor.tolist()

In [18]:
s_2

[-1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 

In [10]:
from numpy import*

In [13]:
S = mat([s_1,s_2])

In [17]:
S = np.transpose(S)
S

matrix([[-1, -1],
        [ 1, -1],
        [-1,  1],
        ...,
        [ 1, -1],
        [-1,  1],
        [ 1,  1]])

In [24]:
# score for two model
c_1 = 0.81183
c_2 = 0.68225
c_mat = np.transpose(mat([c_1,c_2]))
c_mat

matrix([[0.81183],
        [0.68225]])

In [25]:
# ST * y 
k = 120000
STy = k* (2*c_mat - 1)
STy

matrix([[74839.2],
        [43740. ]])

In [35]:
STS = np.transpose(S) * S
STS_inv = STS.I
STS_inv

matrix([[ 9.04444524e-06, -2.53606245e-06],
        [-2.53606245e-06,  9.04444524e-06]])

In [34]:
np.set_printoptions(suppress=False)

In [36]:
W = STS_inv * STy
W

matrix([[0.56595168],
        [0.20580715]])

In [38]:
new_ratings = S * W
new_ratings

matrix([[-0.77175883],
        [ 0.36014452],
        [-0.36014452],
        ...,
        [ 0.36014452],
        [-0.36014452],
        [ 0.77175883]])

In [39]:
new_ratings = new_ratings.T


In [44]:
new_ratings = np.array(new_ratings).reshape((20000,6)).tolist()
new_ratings

[[-0.7717588253670729,
  0.3601445247359644,
  -0.3601445247359644,
  -0.3601445247359644,
  0.3601445247359644,
  0.7717588253670729],
 [-0.3601445247359644,
  0.7717588253670729,
  0.3601445247359644,
  -0.7717588253670729,
  0.7717588253670729,
  -0.7717588253670729],
 [0.3601445247359644,
  -0.7717588253670729,
  0.7717588253670729,
  0.7717588253670729,
  -0.3601445247359644,
  -0.7717588253670729],
 [-0.3601445247359644,
  0.3601445247359644,
  -0.7717588253670729,
  -0.3601445247359644,
  0.7717588253670729,
  0.3601445247359644],
 [-0.7717588253670729,
  -0.7717588253670729,
  0.7717588253670729,
  0.7717588253670729,
  0.7717588253670729,
  -0.7717588253670729],
 [-0.3601445247359644,
  -0.3601445247359644,
  -0.7717588253670729,
  0.7717588253670729,
  0.3601445247359644,
  0.3601445247359644],
 [0.3601445247359644,
  0.3601445247359644,
  -0.3601445247359644,
  -0.7717588253670729,
  0.7717588253670729,
  -0.3601445247359644],
 [-0.3601445247359644,
  -0.7717588253670729,
  

In [45]:
sub_1

TrackID  Predictor
0       199810_208019         -1
1        199810_74139          1
2         199810_9903         -1
3       199810_242681         -1
4        199810_18515          1
5       199810_105760          1
6       199812_276940         -1
7       199812_142408          1
8       199812_130023          1
9        199812_29189         -1
10      199812_223706          1
11      199812_211361         -1
12      199813_188441          1
13       199813_20968         -1
14       199813_21571          1
15       199813_79640          1
16      199813_184173         -1
17      199813_111874         -1
18      199814_122375         -1
19      199814_189043          1
20      199814_122429         -1
21       199814_52519         -1
22      199814_232332          1
23      199814_262193          1
24       199815_64345         -1
25      199815_118841         -1
26      199815_275682          1
27       199815_30062          1
28      199815_258473          1
29      199815_129866         -1
...               ...        ...
119970  248990_255923         -1
119971   248990_61561         -1
119972  248990_133208         -1
119973  248990_285661          1
119974   248990_49802          1
119975   248990_87552          1
119976   248993_87854         -1
119977   248993_65792         -1
119978  248993_192625          1
119979   248993_60331          1
119980   248993_96932         -1
119981  248993_169455          1
119982  248996_125502         -1
119983  248996_130097          1
119984   248996_27528          1
119985   248996_13479         -1
119986   248996_92369         -1
119987  248996_177384          1
119988    249008_4967          1
119989  249008_164591          1
119990  249008_127497         -1
119991  249008_165413          1
119992  249008_197975         -1
119993  249008_239621         -1
119994  249010_110470          1
119995   249010_72192         -1
119996   249010_86104         -1
119997  249010_186634          1
119998  249010_293818         -1
119999  249010_262811          1

[120000 rows x 2 columns]

In [46]:
# Function to create trackID and predicton score table

def prediction_table(grades_table):
    prediction_table = [0 for i in range(len(grades_table)*6)]
    for i in range(len(grades_table)):
        x = np.array(grades_table[i])
        x = x.argsort()

        for k in range(6):
#             prediction_table[i * 6 + k][0] = str(test_set[i][0]) + '_' + str(test_set[i][k + 2])
            if k<3:
                prediction_table[i * 6 + x[k]] = 0
            else:
                prediction_table[i * 6 + x[k]] = 1
      
    return prediction_table

In [47]:
new_ratings_table = prediction_table(new_ratings)
new_ratings_table

[0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,


In [48]:
sub_2.Predictor = new_ratings_table

In [49]:
sub_2

TrackID  Predictor
0       199810_208019          0
1        199810_74139          1
2         199810_9903          0
3       199810_242681          0
4        199810_18515          1
5       199810_105760          1
6       199812_276940          0
7       199812_142408          1
8       199812_130023          1
9        199812_29189          0
10      199812_223706          1
11      199812_211361          0
12      199813_188441          1
13       199813_20968          0
14       199813_21571          1
15       199813_79640          1
16      199813_184173          0
17      199813_111874          0
18      199814_122375          0
19      199814_189043          1
20      199814_122429          0
21       199814_52519          0
22      199814_232332          1
23      199814_262193          1
24       199815_64345          0
25      199815_118841          0
26      199815_275682          1
27       199815_30062          1
28      199815_258473          1
29      199815_129866          0
...               ...        ...
119970  248990_255923          0
119971   248990_61561          0
119972  248990_133208          0
119973  248990_285661          1
119974   248990_49802          1
119975   248990_87552          1
119976   248993_87854          0
119977   248993_65792          0
119978  248993_192625          1
119979   248993_60331          1
119980   248993_96932          0
119981  248993_169455          1
119982  248996_125502          0
119983  248996_130097          1
119984   248996_27528          1
119985   248996_13479          0
119986   248996_92369          0
119987  248996_177384          1
119988    249008_4967          1
119989  249008_164591          1
119990  249008_127497          0
119991  249008_165413          1
119992  249008_197975          0
119993  249008_239621          0
119994  249010_110470          1
119995   249010_72192          0
119996   249010_86104          0
119997  249010_186634          1
119998  249010_293818          0
119999  249010_262811          1

[120000 rows x 2 columns]

In [50]:
sub_2.to_csv('EE627_final_ver12.csv',index = False)